# V2Ray Windows DLL Build Script
# PowerShell version of build.bat

Write-Host "Building V2Ray Windows DLL..." -ForegroundColor Green

# Set environment variables
$env:CGO_ENABLED = "1"
$env:GOOS = "windows"
$env:GOARCH = "amd64"

Write-Host "Environment:" -ForegroundColor Yellow
Write-Host "  CGO_ENABLED = $env:CGO_ENABLED"
Write-Host "  GOOS = $env:GOOS"
Write-Host "  GOARCH = $env:GOARCH"
Write-Host ""

# Build the DLL
Write-Host "Running: go build -buildmode=c-shared -o v2ray.dll main.go" -ForegroundColor Cyan
$buildResult = & go build -buildmode=c-shared -o v2ray.dll main.go 2>&1

if ($LASTEXITCODE -eq 0) {
    Write-Host "Build successful!" -ForegroundColor Green
    Write-Host ""
    Write-Host "Generated files:" -ForegroundColor Yellow
    
    if (Test-Path "v2ray.dll") {
        $dllSize = (Get-Item "v2ray.dll").Length
        Write-Host "  - v2ray.dll ($([math]::Round($dllSize/1MB, 2)) MB)" -ForegroundColor White
    }
    
    if (Test-Path "v2ray.h") {
        Write-Host "  - v2ray.h (auto-generated C header)" -ForegroundColor White
    }
    
    Write-Host ""
    Write-Host "Note: The v2ray.h file is regenerated by Go build." -ForegroundColor Cyan
    Write-Host "Use our custom v2ray.h for better documentation." -ForegroundColor Cyan
    
    Write-Host ""
    Write-Host "To test the DLL:" -ForegroundColor Yellow
    Write-Host "  1. Compile example: gcc -o example.exe example.c" -ForegroundColor White
    Write-Host "  2. Run example: .\example.exe" -ForegroundColor White
} else {
    Write-Host "Build failed!" -ForegroundColor Red
    Write-Host "Error output:" -ForegroundColor Red
    Write-Host $buildResult -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "Press any key to continue..."
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
