@echo off
echo Building V2Ray Windows DLL...

REM Set CGO_ENABLED to 1 to enable CGO
set CGO_ENABLED=1

REM Set GOOS and GOARCH for Windows
set GOOS=windows
set GOARCH=amd64

REM Build the DLL
go build -buildmode=c-shared -o v2ray.dll main.go

if %ERRORLEVEL% EQU 0 (
    echo Build successful! Generated files:
    echo - v2ray.dll (Windows DLL)
    echo - v2ray.h (C header file - will be overwritten by Go)
    echo.
    echo Note: The v2ray.h file will be regenerated by Go build.
    echo Use the custom v2ray.h we created for better documentation.
) else (
    echo Build failed!
    exit /b 1
)

pause
